network_file: "net/onset_and_pitch_0901.py"
network_class_name: "Split_onset_pitch"
use_strongly_dataset: True
training_dataset_dir: "/home/kojiek/side_projects/music-ai/karaoke-jp/benchmarks/retrain/MIR-ST500-RF"
training_gt_pkl_label: "/home/kojiek/side_projects/music-ai/karaoke-jp/benchmarks/retrain/train_strong_ctcce30.pkl"
use_weakly_dataset: True
training_weakly_dataset_dir: "/home/kojiek/side_projects/music-ai/karaoke-jp/benchmarks/retrain/MIR-ST500-RF"
training_weakly_gt_pkl_label: "/home/kojiek/side_projects/music-ai/karaoke-jp/benchmarks/retrain/train_weak.pkl"
val_dataset_dir: "/home/kojiek/side_projects/music-ai/karaoke-jp/benchmarks/retrain/val_set-RF"
val_gt_pkl_label: "/home/kojiek/side_projects/music-ai/karaoke-jp/benchmarks/retrain/val_strong_ctcce30.pkl"
h5py_feature_file_name: "feature.hdf5"
epoch: 100
warmup_epoch: 5
lr: 0.0001
batch_size: 1
model_save_dir: "/home/kojiek/side_projects/music-ai/karaoke-jp/benchmarks/retrain/models"
model_save_prefix: "ctc_ce_rf"
log_path: "/home/kojiek/side_projects/music-ai/karaoke-jp/benchmarks/retrain/logger_ctc_ce_rf.pkl"
